name: PR Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'Restream/reindexer-java'

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Reindexer
        run: |
          curl http://repo.reindexer.io/RX-KEY.GPG | sudo apt-key add
          echo 'deb http://repo.reindexer.io/ubuntu-bionic /' | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install reindexer-dev
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
