name: PR Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-24.04
    if: github.repository == 'Restream/reindexer-java'

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Install Reindexer
        run: |
          sudo curl https://repo.reindexer.io/RX-KEY.GPG -o /etc/apt/trusted.gpg.d/reindexer.asc
          echo 'deb https://repo.reindexer.io/ubuntu-noble /' | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install reindexer-dev
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
