name: Release Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04
    if: github.repository == 'Restream/reindexer-java'
    env:
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE_1 }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY_1 }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Install Reindexer
        run: |
          sudo curl https://repo.reindexer.io/RX-KEY.GPG -o /etc/apt/trusted.gpg.d/reindexer.asc
          echo 'deb https://repo.reindexer.io/ubuntu-noble /' | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y reindexer-dev libopenblas-pthread-dev

      - name: Prepare release
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          mvn --batch-mode release:prepare -Psign-artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          server-id: sonatype-nexus-staging
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Perform release
        run: |
          mvn --batch-mode release:perform -Psign-artifacts
          curl --request POST \
               --user "${{ secrets.MAVEN_USERNAME_1 }}:${{ secrets.MAVEN_PASSWORD_1 }}" \
               --url "https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/manual/upload/defaultRepository/com.github.restream"
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME_1 }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD_1 }}
